# 键盘布局
# Keyboard=Dubeolsik
# 自动排序
# AutoReorder=True
# 组合双辅音
# CombiOnDoubleStroke=False
# 组合非词首辅音
# NonChoseongCombi=True
# 单词提交
# WordCommit=False
# 汉字模式
# HanjaMode=False

# [HanjaModeToggleKey]
# 0=Hangul_Hanja
# 1=F9

# [PrevPage]
# 0=Up

# [NextPage]
# 0=Down

# [PrevCandidate]
# 0=Shift+Tab

# [NextCandidate]
# 0=Tab

