#导入主题
include dark-theme.conf

#窗口字号
font_size 13
# 基础字体
font_family      JetBrainsMono Nerd Font
# 粗体变体 (通常对应 Bold 或 Medium 字重)
bold_font        JetBrainsMono Nerd Font Bold
# 斜体变体
italic_font      JetBrainsMono Nerd Font Italic
# 粗斜体变体
bold_italic_font JetBrainsMono Nerd Font Bold Italic

#窗口设置
#hide_window_decorations		titlebar-only
window_padding_width		15
#毛玻璃效果
background_opacity 		0.68
background_blur			40

#tab bar
tab_bar_edge			top
tab_bar_style 			powerline
tab_powerline_style		slanted

